powerConsumption<-read.table("household_power_consumption.txt",na.strings = "?",sep =";" ,header = T)
powerConsumption$Date<-as.Date(powerConsumption$Date,format = "%d/%m/%Y")
powerConsumption<-subset(powerConsumption,Date == "2007-02-01" | Date == "2007-02-02" )
powerConsumption$Date<-paste(powerConsumption$Date,powerConsumption$Time)
powerConsumption$Date<-strptime(powerConsumption$Date,"%Y-%m-%d %H:%M:%S")
png(filename = "plot2.png",width = 480,height = 480)
plot(powerConsumption$Date,powerConsumption$Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)",xlab = "")
dev.off()
