powerConsumption<-read.table("household_power_consumption.txt",na.strings = "?",sep =";" ,header = T)
powerConsumption$Date<-as.Date(powerConsumption$Date,format = "%d/%m/%Y")
powerConsumption<-subset(powerConsumption,Date == "2007-02-01" | Date == "2007-02-02" )
png(filename = "plot1.png",width = 480,height = 480)
hist(powerConsumption$Global_active_power,col="red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()
